"""Lightweight backend server to host the RB-UNet UI and expose real ML inference APIs."""

import base64
from http.server import HTTPServer, SimpleHTTPRequestHandler
import io
import json
import os
from pathlib import Path
import sys
import time
from urllib.parse import parse_qs, urlparse
from PIL import Image
import numpy as np
import torch
import torchvision.transforms.functional as TF

sys.path.insert(0, str(Path(__file__).resolve().parent))

from src.models.rb_unet import RBUNet
from src.models.unet import UNet
from src.training.checkpoint import load_checkpoint
from src.utils.visualization import create_overlay

PORT = 8000
BASE_DIR = Path(__file__).resolve().parent
UI_DIR = BASE_DIR / "ui"
OUTPUTS_DIR = BASE_DIR / "outputs"


class RBUNetServerHandler(SimpleHTTPRequestHandler):
    """Custom HTTP handler serving UI and REST API."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(UI_DIR), **kwargs)

    def do_GET(self):
        parsed = urlparse(self.path)

        if parsed.path == "/api/results":
            self.handle_get_results()
        elif parsed.path == "/api/status":
            self.handle_get_status()
        elif parsed.path.startswith("/outputs/"):
            # Serve files from outputs/ directory
            file_rel = parsed.path.replace("/outputs/", "")
            file_path = OUTPUTS_DIR / file_rel
            if file_path.exists() and file_path.is_file():
                self.send_response(200)
                if file_path.suffix == ".png":
                    self.send_header("Content-Type", "image/png")
                elif file_path.suffix == ".jpg":
                    self.send_header("Content-Type", "image/jpeg")
                elif file_path.suffix == ".json":
                    self.send_header("Content-Type", "application/json")
                else:
                    self.send_header("Content-Type", "application/octet-stream")
                self.end_headers()
                with open(file_path, "rb") as f:
                    self.wfile.write(f.read())
            else:
                self.send_error(404, "File not found")
        else:
            super().do_GET()

    def do_POST(self):
        parsed = urlparse(self.path)
        if parsed.path == "/api/segment":
            self.handle_segment_image()
        else:
            self.send_error(404, "Unknown API endpoint")

    def handle_get_status(self):
        status = {
            "system": "RB-UNet Research System",
            "device": "CUDA" if torch.cuda.is_available() else "CPU",
            "best_checkpoint_exists": (OUTPUTS_DIR / "checkpoints/full_rb_unet_latest.pth").exists(),
            "baseline_checkpoint_exists": (OUTPUTS_DIR / "checkpoints/baseline_unet_latest.pth").exists(),
        }
        self.send_json_response(status)

    def handle_get_results(self):
        """Reads real outputs generated by training and evaluation pipelines."""
        results = {
            "ablation": [],
            "robustness": [],
            "final_test": None,
            "dataset_report": None,
        }

        # Ablation summary
        abl_file = OUTPUTS_DIR / "ablations/ablation_summary.json"
        if abl_file.exists():
            with open(abl_file, "r", encoding="utf-8") as f:
                results["ablation"] = json.load(f)

        # Robustness results
        rob_file = OUTPUTS_DIR / "robustness/robustness_results.json"
        if rob_file.exists():
            with open(rob_file, "r", encoding="utf-8") as f:
                results["robustness"] = json.load(f)

        # Final test results
        test_file = OUTPUTS_DIR / "metrics/final_test_results.json"
        if test_file.exists():
            with open(test_file, "r", encoding="utf-8") as f:
                results["final_test"] = json.load(f)

        # Dataset report
        ds_file = OUTPUTS_DIR / "metrics/dataset_report.json"
        if ds_file.exists():
            with open(ds_file, "r", encoding="utf-8") as f:
                results["dataset_report"] = json.load(f)

        self.send_json_response(results)

    def handle_segment_image(self):
        """Runs live segmentation inference on an uploaded image."""
        try:
            content_length = int(self.headers["Content-Length"])
            post_data = self.rfile.read(content_length)
            body = json.loads(post_data.decode("utf-8"))

            image_b64 = body.get("image")
            if not image_b64:
                self.send_error(400, "Missing image base64")
                return

            if "," in image_b64:
                image_b64 = image_b64.split(",", 1)[1]

            image_bytes = base64.b64decode(image_b64)
            img = Image.open(io.BytesIO(image_bytes)).convert("RGB")

            device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            img_size = 256
            resized = TF.resize(img, [img_size, img_size], interpolation=TF.InterpolationMode.BILINEAR)
            t_img = TF.to_tensor(resized)
            norm = TF.normalize(t_img, [0.485, 0.456, 0.406], [0.229, 0.224, 0.225]).unsqueeze(0).to(device)

            # Load model
            ckpt_path = OUTPUTS_DIR / "checkpoints/full_rb_unet_latest.pth"
            if not ckpt_path.exists():
                ckpt_path = OUTPUTS_DIR / "checkpoints/sanity_test.pth"

            if ckpt_path.exists():
                from src.training.checkpoint import build_model_from_checkpoint
                model = build_model_from_checkpoint(str(ckpt_path), device=str(device))
            else:
                features = [16, 32, 64, 128, 256]
                model = RBUNet(in_channels=3, out_channels=1, features=features, boundary_head_channels=16).to(device)
            model.eval()

            t0 = time.time()
            with torch.no_grad():
                out = model(norm)
            infer_ms = (time.time() - t0) * 1000.0

            seg_logits = out["seg_logits"]
            bnd_logits = out.get("boundary_logits")

            prob = torch.sigmoid(seg_logits).squeeze().cpu().numpy()
            pred_mask = (prob > 0.5).astype(np.uint8)

            lesion_pct = float((np.sum(pred_mask) / pred_mask.size) * 100.0)

            # Generate overlay
            img_np = np.array(resized)
            overlay_np = create_overlay(img_np, pred_mask, color=(0, 210, 180), alpha=0.45)

            # Boundary map
            bnd_np = None
            if bnd_logits is not None:
                bnd_prob = torch.sigmoid(bnd_logits).squeeze().cpu().numpy()
                bnd_np = (bnd_prob > 0.5).astype(np.uint8)

            def to_b64_png(arr: np.ndarray) -> str:
                if arr.ndim == 2:
                    im = Image.fromarray(arr * 255)
                else:
                    im = Image.fromarray(arr)
                buf = io.BytesIO()
                im.save(buf, format="PNG")
                return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("utf-8")

            res_payload = {
                "success": True,
                "lesion_area_pct": round(lesion_pct, 1),
                "inference_time_ms": round(infer_ms, 1),
                "model_name": "RB-UNet",
                "output_type": "Binary Segmentation Mask",
                "original": to_b64_png(img_np),
                "mask": to_b64_png(pred_mask),
                "overlay": to_b64_png(overlay_np),
                "boundary": to_b64_png(bnd_np) if bnd_np is not None else None,
            }
            self.send_json_response(res_payload)

        except Exception as e:
            self.send_json_response({"success": False, "error": str(e)}, status=500)

    def send_json_response(self, data: dict, status: int = 200):
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(json.dumps(data).encode("utf-8"))


def serve():
    UI_DIR.mkdir(parents=True, exist_ok=True)
    server_address = ("", PORT)
    httpd = HTTPServer(server_address, RBUNetServerHandler)
    print("=" * 65)
    print(f"RB-UNet Medical Research Interface running at: http://localhost:{PORT}")
    print("=" * 65)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")


if __name__ == "__main__":
    serve()
